---
title: "Negative Incentive Framing Structures in Cognitively Demanding Tasks"
author: "Tshering Wangchuk and Franco Salinas Meza"
output: github_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = TRUE, warning = FALSE, message = FALSE)

library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(sf)
library(spdep)
library(spatialreg)
library(ggthemes)
```

```{r, results='hide'}
experiment<- read.csv('Data.csv')
data<-as.data.frame(experiment)
data_clean<- data %>% 
  filter(SL<30) %>% 
  select(-X,-X.1) 

##Given the low number of first years we could create two variables, one that it lower and upper classmen 

data_clean<-data_clean %>% 
  mutate(school_status = ifelse(test = School_Year == 1|School_Year==2, yes = "Underclassmen",no = "Upperclassmen"))

##Given the low number of subjects in certain majors I grouped them into Stem and Social Science

NEW_MAJOR_CATEGORY<-data_clean %>% 
  mutate(Major_category = ifelse(Major=="Biology"|Major=="Computer Science"|Major=="Geology"|Major=="Neuroscience"|Major=="Statistics","STEM","Social Science")) %>% 
  mutate(accuracy_rate = Correct/12, share_questions_responded = (Passage.1+Passage.2)/12)
```

```{r}

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = Major_category,y = accuracy_rate), fill = blue)+
  geom_boxplot()+
  labs(title = "Figure 1: Accuracy Rate vs. Major Category",
       x=  "Major Category",
       y=  "Accuracy Rate")+
  theme_classic()
 
  

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = factor(school_status)))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. School Year",
       x=  "School Year",
       y=  "Accuracy Rate")+
  theme_classic()


NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = factor(English_Native)))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. Indicator of whether the Person is a Native Speaker",
       x=  "Is the subject a Native Speaker?",
       y=  "Accuracy Rate")+
  theme_classic()


NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = factor(Incentive_Structure)))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. Incentive Structure",
       x=  "Incentive Structure",
       y=  "Accuracy Rate")+
  theme_classic()


NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = factor(International)))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. Indicator if it's an international Student",
       x=  "Is the subject an International Student?",
       y=  "Accuracy Rate")+
  theme_classic()



NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = accuracy_rate, y = Guess))+
  geom_point()+
  labs(title = "Changes in accuracy rate with Number of Guesses")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = accuracy_rate, y = Hours_of_Sleep))+
  geom_point()+
  labs(title = "Changes in accuracy rate with Hours of Sleep")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = accuracy_rate, y = Number_of_Classes))+
  geom_point()+
  labs(title = "Changes in accuracy rate with Number of Classes")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = Workload))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. Workload",
       x=  "Is the subject experiencing a large or small workload?",
       y=  "Accuracy Rate")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = accuracy_rate, y = Gender))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. Indicator for Gender",
       x=  "Is the subject male or female identifying?",
       y=  "Accuracy Rate")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = share_questions_responded, x = Incentive_Structure))+
  geom_boxplot()+
  labs(title = "Figure 2: Share of Questions Responded vs. Incentive Structure",
       x=  "Is the subject male or female identifying?",
       y=  "Accuracy Rate")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = share_questions_responded))+
  geom_density(fill = "blue")+
  labs(title = "Figure 2: Distribution of Share of Questions Responded",
       y=  "Probability",
       x=  "Number of questions responded")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = Gender))+
  geom_bar()+
  labs(title = "Figure 2: Distribution of Share of Questions Responded",
       y=  "Probability",
       x=  "Number of questions responded")+
  theme_classic()
  
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = Major_category))+
  geom_bar()+
  labs(title = "Figure 2: Distribution of Share of Questions Responded",
       y=  "Probability",
       x=  "Number of questions responded")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = school_status))+
  geom_bar()+
  labs(title = "Figure 2: Distribution of Share of Questions Responded",
       y=  "Probability",
       x=  "Number of questions responded")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = English_Native))+
  geom_bar()+
  labs(title = "Figure 2: Distribution of Share of Questions Responded",
       y=  "Probability",
       x=  "Number of questions responded")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = International))+
  geom_bar()+
  labs(title = "Figure 2: Distribution of Share of Questions Responded",
       y=  "Probability",
       x=  "Number of questions responded")+
  theme_classic()

NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(x = Incentive_Structure))+
  geom_bar()+
  labs(title = "Figure 2: Distribution of Share of Questions Responded",
       y=  "Probability",
       x=  "Number of questions responded")+
  theme_classic()



NEW_MAJOR_CATEGORY %>% 
  select(accuracy_rate, Number_of_Classes, Hours_of_Sleep, share_questions_responded) %>% 
  cor()

```

## Understanding Factors that affect accuracy

```{r}
model1 <- lm(accuracy_rate~Incentive_Structure*Gender+Gender+school_status+English_Native+Number_of_Classes+Hours_of_Sleep+Workload+Major_category+share_questions_responded,data = NEW_MAJOR_CATEGORY)
summary(model1)
```


```{r}


library(huxtable)

huxreg(model1)


# tab <- huxreg(model1,
#               # Rename coefficients
#               coefs = c("Incentive Structure" = "Incentive_StructurePositive", "Male" = "GenderMale", "Upperclassmen" = "factor(school_status)Upperclassmen","English Native Speaker" = "English_NativeYes"),
#               # Add the desired summary statistics
#               statistics = c(N = "nobs", R2 = "r.squared", p-value = ""),
#               # Add a note
#               note = "Note. Important note about this table") %>% 
#   # Convert the huxtable table to flextable
#   as_flextable()
# 
# # Set a custom width to ensure it fits on the page
# tab %>% flextable::width(width = 1)

```


### Incentive Structure

```{r}
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = factor(Incentive_Structure)))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. Incentive Structure",
       x=  "Incentive Structure",
       y=  "Accuracy Rate")+
  theme_classic()
```

### School Year Status

```{r}
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = factor(school_status)))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. School Year",
       x=  "School Year",
       y=  "Accuracy Rate")+
  theme_classic()
```

### English as a Native Language

```{r}
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = accuracy_rate, x = factor(English_Native)))+
  geom_boxplot()+
  labs(title = "Figure 2: Accuracy Rate vs. Indicator of whether the Person is a Native Speaker",
       x=  "Is the subject a Native Speaker?",
       y=  "Accuracy Rate")+
  theme_classic()
```


## Understanding Factors that affect the share of questions responded: 

```{r}
model2<-lm(share_questions_responded~Incentive_Structure+Gender+factor(school_status)+English_Native+Number_of_Classes+Hours_of_Sleep+Workload+Major_category+share_questions_responded,data = NEW_MAJOR_CATEGORY)
summary(model2)

```

```{r}
huxreg(model2)
```



```{r}
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = share_questions_responded, x = Incentive_Structure))+
  geom_boxplot()+
  labs(title = "Figure 2: Share of Questions Responded vs. Incentive Structure",
       x=  "Is the subject male or female identifying?",
       y=  "Accuracy Rate")+
  theme_classic()

```

```{r}
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = share_questions_responded, x = Number_of_Classes))+
  geom_boxplot()+
  labs(title = "Figure 2: Share of Questions Responded vs. Incentive Structure",
       x=  "Is the subject male or female identifying?",
       y=  "Accuracy Rate")+
  theme_classic()

```

```{r}
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = share_questions_responded, x = Hours_of_Sleep))+
  geom_boxplot()+
  labs(title = "Figure 2: Share of Questions Responded vs. Incentive Structure",
       x=  "Is the subject male or female identifying?",
       y=  "Accuracy Rate")+
  theme_classic()

```

```{r}
NEW_MAJOR_CATEGORY %>% 
  ggplot(aes(y = share_questions_responded, x = Workload))+
  geom_boxplot()+
  labs(title = "Figure 2: Share of Questions Responded vs. Incentive Structure",
       x=  "Is the subject male or female identifying?",
       y=  "Accuracy Rate")+
  theme_classic()

```

